### ISSUE TITLE
Archive old documents instead of deleting them

### ISSUE THREAD

**Issue by mswider** [codeths/kitcoin#111]
Deleting old documents means we can't always completely determine past actions, like who sent a transaction, what items were in a store, and also stores that have existed.

### Todo:
- [x] Update Document schemas to add `archived` property
- [x] Update Models to add `.archive()` method
- [x] Replace calls to `remove()` with `archive()`
- [x] Modify applicable queries to exclude archived Documents

**Comment by mswider** [comment]
@edcous Which Documents should be included here?
I think we should include Users, Stores, and StoreItems

**Comment by edcous** [comment]
Yeah, I don’t see a need to archive StoreRequests, and I don’t think there are any other types that are ever deleted.On Sep 13, 2023, at 9:42 AM, mswider ***@***.***> wrote:﻿
@edcous Which Documents should be included here?
I think we should include Users, Stores, and StoreItems
