### ISSUE TITLE
Staff Balance Rework

### ISSUE THREAD

**Issue by mswider** [codeths/kitcoin#122]
## The problem
As an administrator, you (currently) don't have really any control of budgeting. This isn't good!
In addition, even with effective budgeting, we have to maintain economic stability and ensure that Staff aren't too eager to give away all of their Kitcoin too quickly.

## The solution
By reworking how staff balances function, we can solve both problems at the same time, and make Kitcoin more fun.

### Terms

- **The Pot:** A large sum of Kitcoin that administrators allocate to the program for distribution
- **Share:** A portion of **The Pot** which is allocated to a Staff member for the given school year
- **Allowance:** A portion of a **Share** which is available for Staff to award to students

### How it works
- Before the school year begins, administrators determine the yearly budget for Kitcoin, which is called The Pot.
- They will also select an interval at which Allowances activate for Staff. (By month, quarter, semester)
- At the beginning of the school year, Shares are evenly allocated to every Staff member, though all but the FIRST Allowance are frozen. 
- When this happens, Staff balances are SET to their first Allowance.
- Throughout the school year, as Allowances are activated, they get ADDED to Staff balances. This helps Staff members manage their budget.
- As needed, administrators can change Shares, and by extension, Allowances for individual Staff members on a case-by-case basis.

### To-Do

- [ ] Create admin interface
  - [ ] Manage The Pot
  - [ ] Control Allowance activation intervals
  - [ ] Control Shares for Staff
- [ ] Create Staff balance overview & visualization
